version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wedding-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wedding_events
      MYSQL_USER: wedding_user
      MYSQL_PASSWORD: wedding_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: wedding-app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: wedding_user
      DB_PASSWORD: wedding_password
      DATABASE_URL: jdbc:mysql://mysql:3306/wedding_events?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
